Data download for individual tools
ExoCTK/exoctk pull request #488
Opened 2021-04-14 05:09 UTC by hover2pi

Resolves #386 by allowing ExoCTK data to be downloaded as needed for each tool.

2021-04-14 05:09 UTC, pep8speaks commented
Hello @hover2pi, Thank you for submitting the Pull Request !

* In the file [`exoctk/contam_visibility/field_simulator.py`](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py):

> [Line 81:1](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L81): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 165:24](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L165): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 167:24](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L167): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 172:75](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L172): [W504](https://duckduckgo.com/?q=pep8%20W504) line break after binary operator
> [Line 182:37](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L182): [W504](https://duckduckgo.com/?q=pep8%20W504) line break after binary operator
> [Line 270:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L270): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 289:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L289): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 294:30](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L294): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 313:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L313): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 348:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L348): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 357:22](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L357): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 359:22](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L359): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 391:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L391): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 402:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L402): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 422:39](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L422): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 501:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L501): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 524:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L524): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 543:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L543): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 548:30](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L548): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 567:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L567): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 602:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L602): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 611:22](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L611): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 613:22](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L613): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 644:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L644): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 655:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L655): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 671:39](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L671): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets
> [Line 785:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/contam_visibility/field_simulator.py#L785): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

* In the file [`exoctk/forward_models/forward_models.py`](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/forward_models/forward_models.py):

> [Line 20:1](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/forward_models/forward_models.py#L20): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 39:1](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/forward_models/forward_models.py#L39): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 41:1](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/forward_models/forward_models.py#L41): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 77:41](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/forward_models/forward_models.py#L77): [W504](https://duckduckgo.com/?q=pep8%20W504) line break after binary operator
> [Line 78:17](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/forward_models/forward_models.py#L78): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 80:5](https://github.com/ExoCTK/exoctk/blob/811c130c27b5e0b08a32a0680205003a304b3c74/exoctk/forward_models/forward_models.py#L80): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 117:79](https:// [...]

2021-04-14 05:09 UTC, hover2pi commented
There is exactly a 0% chance the tests pass on this one on my first try.

2021-04-22 14:35 UTC, bourque requested changes
After initial review, the code changes look good to me.  However, importing `exoctk` crashes upon testing (see comment on `utils.py`).

2021-04-22 14:35 UTC, bourque commented on exoctk/contam_visibility/field_simulator.py
> +#     TRACES_PATH = os.path.join(EXOCTK_DATA, 'exoctk_contam', 'traces')
Could we just remove this instead of leaving it in and commented out?

2021-04-22 14:35 UTC, bourque commented on exoctk/utils.py
> +            'download folder.  Users may retrieve this folder by clicking the '
Nice catch 😆 .  "I before E except after C"

2021-04-22 14:35 UTC, bourque commented on exoctk/utils.py
> +NON_JWST = [filt for filt in FILTERS if not filt.startswith('NIRISS') and not filt.startswith('NIRCam') and not filt.startswith('NIRSpec') and not filt.startswith('MIRI')]
@hover2pi This line appears to be crashing when trying to `import exoctk`:

```
>>> import exoctk
pandeia not installed. Functionality limited.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/__init__.py", line 10, in <module>
    from . import modelgrid
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/modelgrid.py", line 24, in <module>
    from . import utils
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/utils.py", line 30, in <module>
    NON_JWST = [filt for filt in FILTERS if not filt.startswith('NIRISS') and not filt.startswith('NIRCam') and not filt.startswith('NIRSpec') and not filt.startswith('MIRI')]
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/utils.py", line 30, in <listcomp>
    NON_JWST = [filt for filt in FILTERS if not filt.startswith('NIRISS') and not filt.startswith('NIRCam') and not filt.startswith('NIRSpec') and not filt.startswith('MIRI')]
AttributeError: 'Row' object has no attribute 'startswith'
```

2021-04-27 15:10 UTC, hover2pi commented
@bourque Ok, I realized I didn't update the env files. Thanks!

2021-04-27 17:30 UTC, bourque commented
@hover2pi FYI, I pulled you most recent changes and I am still seeing the same error as before:

```
>>> import exoctk
pandeia not installed. Functionality limited.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/__init__.py", line 10, in <module>
    from . import modelgrid
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/modelgrid.py", line 24, in <module>
    from . import utils
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/utils.py", line 30, in <module>
    NON_JWST = [filt for filt in FILTERS if not filt.startswith('NIRISS') and not filt.startswith('NIRCam') and not filt.startswith('NIRSpec') and not filt.startswith('MIRI')]
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/utils.py", line 30, in <listcomp>
    NON_JWST = [filt for filt in FILTERS if not filt.startswith('NIRISS') and not filt.startswith('NIRCam') and not filt.startswith('NIRSpec') and not filt.startswith('MIRI')]
AttributeError: 'Row' object has no attribute 'startswith'
```

2021-04-27 17:53 UTC, hover2pi commented
@bourque can you check if it's running `svo_filters` v0.4.1? That's the only thing that can be breaking it. Thanks!

2021-04-27 18:35 UTC, bourque commented
@hover2pi Ah yes, good point.  I updated `svo_filters` and that appears to solve that problem, but a new one arises:

```
>>> import exoctk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/__init__.py", line 10, in <module>
    from . import modelgrid
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/modelgrid.py", line 24, in <module>
    from . import utils
  File "/Users/bourque/Desktop/repositories/exoctk/exoctk/utils.py", line 19, in <module>
    from svo_filters import svo
  File "/Users/bourque/miniconda3/envs/exoctk-3.7/lib/python3.7/site-packages/svo_filters/__init__.py", line 1, in <module>
    from .svo import Filter
  File "/Users/bourque/miniconda3/envs/exoctk-3.7/lib/python3.7/site-packages/svo_filters/svo.py", line 17, in <module>
    from astroquery.svo_fps import SvoFps
ModuleNotFoundError: No module named 'astroquery.svo_fps'
```

Which version of `astroquery` are you using?  The one that comes with the `exoctk-3.7` environment doesn't appear to be working with this.

2021-04-27 19:14 UTC, hover2pi commented
Oh yeah. It requires `git+https://github.com/astropy/astroquery.git@ccc96185beeff86f3a12a31a00a801afcebe1dbe`, which is astroquery v0.4.2.dev####. I'll add that to the env files.

2021-04-27 19:17 UTC, hover2pi commented
Ok, that should do it @bourque . Sorry to make you look at this so many times.

2021-04-27 19:41 UTC, bourque approved these changes

2021-04-27 20:00 UTC, merged